---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-job-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctf-job-role
rules:
- apiGroups: ["neuvector.com"]
  resources: ["nvadmissioncontrolsecurityrules"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctf-job-rolebinding
subjects:
- kind: ServiceAccount
  name: ctf-job-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ctf-job-role
  apiGroup: rbac.authorization.k8s.io
